# Generated by Django 4.0.1 on 2022-01-29 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='createur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='possesseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='possesseur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
