# Generated by Django 4.0.1 on 2022-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='transferable_status',
            field=models.CharField(choices=[('DISP', 'Disponible'), ('LECT', 'Lecture'), ('PERD', 'Perdu')], default='DISP', max_length=4),
        ),
    ]
