# Generated by Django 4.0.1 on 2022-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_livre_transferable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteur_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
