# Generated by Django 4.0.1 on 2022-01-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0005_livre_auteur_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='livre_code',
            field=models.CharField(default='aaaa', max_length=20),
            preserve_default=False,
        ),
    ]
