# Generated by Django 4.0.1 on 2022-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0006_livre_livre_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='livre_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='livre',
            name='publication_date',
            field=models.DateField(blank=True, verbose_name='date publication'),
        ),
    ]
