# Generated by Django 4.0.1 on 2022-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0009_transfert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
