# Generated by Django 4.0.1 on 2022-01-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livres', '0010_alter_transfert_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='demandeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demandeurtsf', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfert',
            name='possesseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='possesseurtsf', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfert',
            name='transfert_status',
            field=models.CharField(choices=[('INIT', 'INITIALISER'), ('OKPO', 'OKPOSSESSEUR'), ('OKDE', 'OKDEMANDEUR'), ('CANCEL', 'CANCEL')], default='INIT', max_length=6),
        ),
    ]
