# Generated by Django 4.0.1 on 2022-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0011_transfert_demandeur_transfert_possesseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='ok_demandeur_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transfert',
            name='ok_possesseur_date',
            field=models.DateField(null=True),
        ),
    ]
