# Generated by Django 4.0.1 on 2022-01-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0012_transfert_ok_demandeur_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='ok_possesseur_date',
            field=models.DateField(null=True, verbose_name='date possesseur a transfere'),
        ),
    ]
