# Generated by Django 4.0.1 on 2022-01-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0013_alter_transfert_ok_possesseur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='ok_demandeur_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='ok_possesseur_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
