# Generated by Django 4.0.1 on 2022-02-01 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livres', '0015_alter_livre_publication_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='possesseur',
        ),
        migrations.AddField(
            model_name='transfert',
            name='possesseur_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possesseurfinaltsf', to=settings.AUTH_USER_MODEL),
        ),
    ]
