# Generated by Django 4.0.1 on 2022-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0016_remove_transfert_possesseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='demandeur_cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
