# Generated by Django 4.0.1 on 2022-02-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0017_transfert_demandeur_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='url_externe_livre_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transfert',
            name='possesseur_envois_message_date',
            field=models.DateField(auto_now=True),
        ),
    ]
