# Generated by Django 4.0.1 on 2022-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0018_livre_url_externe_livre_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='possesseur_envois_message_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
