# Generated by Django 4.0.2 on 2022-02-20 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livres', '0022_livre_possede_depuis_date_alter_livre_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='mots_sujets_txt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(editable=False)),
                ('emprunteur_message_init_retour_date', models.DateField(blank=True, null=True)),
                ('proprietaire_message_reclame_retour_date', models.DateField(blank=True, null=True)),
                ('retour_status', models.CharField(choices=[('ACTIF', 'ACTIF'), ('ACHEVE', 'Acheve'), ('CANCEL', 'CANCEL')], default='ACTIF', max_length=10)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunteur', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.livre')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
