# Generated by Django 4.0.2 on 2022-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0024_retour_emprunteur_retourne_livre_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='categories',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='retour',
            name='retour_status',
            field=models.CharField(choices=[('ACTIF', 'ACTIF'), ('ACHEVE', 'ACHEVE'), ('CANCEL', 'CANCEL')], default='ACTIF', max_length=10),
        ),
    ]
